version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-interiors
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - interiors-network

  # Optional: Redis Commander for web-based Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - interiors-network

volumes:
  redis_data:

networks:
  interiors-network:
    driver: bridge
